### ISSUE TITLE
Unable to generate binding. Authorization Failed

### ISSUE THREAD

**Issue by ShardulNalegave** [go-gl/glow#106]
**OS:** Windows 10

There is a problem with glow. I followed all the steps mentioned in the `README` and everything was ok till `glow download`. The script runs and asks for Github credentials but fails everytime. I checked my credentials and tried about 10-15 times, but no success.

Please help me in setting up OpenGL.

**Comment by drewwoods** [comment]
You need to create a token to your github account, follow https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token

**Comment by dmitshur** [comment]
In case you missed it, there are pre-generated OpenGL bindings in https://github.com/go-gl/gl. `glow` is mostly for developers or for generating something more custom.
