### ISSUE TITLE
Three actions remaining to complete early 2015 overhaul plan.

### ISSUE THREAD

**Issue by shurcooL** [go-gl/glow#52]
Now that the glow-generated bindings have been moved to `go-gl/gl` repo (see go-gl/gl#1), we need to make some follow up PRs for glow:

- [x] Add a removal notice to warn than the gl bindings import paths have changed and will be removed in 30 days as per the document. Similar to go-gl/glfw3#1.

- [x] Make changes to glow to allow it to generate the new bindings with changed import paths. Ideally, I think we should be able to generate the gl bindings from the gl repo by doing `go generate`.
    - Open PRs https://github.com/go-gl/glow/pull/56 and https://github.com/go-gl/gl/pull/9 to resolve this task.

- [ ] Actually remove the gl bindings in 30 days.

**Comment by shurcooL** [comment]
I'm taking on second task.

I'll make a branch with 2nd and 3rd tasks complete and turn it into a PR that we can merge on March 22.

There will be a PR for this repo as well as for gl.

The general idea is to add the necessary missing flags to glow such that `gl` repo can generate everything it needs from there. So, `gl` will pull, rather than than `glow` pushing.

**Comment by shurcooL** [comment]
Question, the [`procaddr`](https://github.com/go-gl/glow/tree/master/procaddr) subfolder and packages are not generated, they are hand-written, is that right?

**Comment by slimsag** [comment]
> Question, the procaddr subfolder and packages are not generated, they are hand-written, is that right?

Yes, that's correct.

**Comment by shurcooL** [comment]
I think we'll need to do something about them. Right now they are manually copied and pasted from `glow` to `gl`, with manual fixes to import paths.

Once the `gl` bindings are removed from `glow` repo, where does the canonical source of `procaddr` live? If in `glow`, then we need to copy/paste/update import paths to `gl`. If in `gl` only, it doesn't quite make sense as the `procaddr` is a part that `glow` depends on when generating its bindings.

I guess we can address `procaddr` later on, but it needs to be done eventually.

**Comment by slimsag** [comment]
Everything below `procaddr` according to godoc.org is not imported by anyone except github.com/go-gl/glow/* and github.com/errcw/glow/* -- and it seems painful to have `procaddr` sit in two places.

I vote for putting `procaddr` into the generated Glow sources. It might add some slight code duplication, but would make many other things easier overall.

**Comment by shurcooL** [comment]
> I vote for putting `procaddr` into the generated Glow sources (for example, a `procaddr.c` file inside each GL package).

That sounds good to me. Any thoughts on this, @errcw?

**Comment by errcw** [comment]
What mechanism would you use to support this design? Simply copy the contents of `procaddr` into each generated package? It's not unreasonable if we consider each package a self-contained entity unto itself, which is likely a reasonable assumption in the face of the majority use case. I'm not thrilled about the code duplication but it's probably the lesser of the evils.

**Comment by slimsag** [comment]
We can use a single .c file in each generated packet, and use the C
compilers preprocessor to build the appropriate  function. Basically
merging all procaddr/ packages into one.

I will try to send a PR this week, if not then 2 weeks max.

**Comment by errcw** [comment]
How will you collapse the `auto` package? Or plumb the `egl` build tag into the appropriate preprocessor declaration?

**Comment by slimsag** [comment]
Build tags (and hence, the auto package) can be passed to the preprocessor
using -DFOO on a #cgo CFLAGS line.
