### ISSUE TITLE
Pointer checks in Go 1.6

### ISSUE THREAD

**Issue by EtienneBruines** [go-gl/glow#66]
Would this be something that should be fixed here, instead of in `github.com/go-gl/gl`?

https://github.com/go-gl/gl/issues/31

**Comment by shurcooL** [comment]
Yes, once we figure out what the fix is, `glow` should be updated and `go-gl/gl` can be regenerated using the new version.

**Comment by shurcooL** [comment]
This has been resolved. Please see https://github.com/go-gl/examples/pull/52/files for example usage.
