### ISSUE TITLE
Unmaintained project?

### ISSUE THREAD

**Issue by dv343** [go-gl/glow#78]
I reported an issue 7 months ago, no one comment on it. Is this still maintained?

**Comment by pwaller** [comment]
I see you're referring to #77. Let's continue the discussion over there.

This project is maintained, but perhaps not quickly! There are several [people who are maintainers](https://github.com/orgs/go-gl/people) and we're happy to welcome new maintainers who are willing to put in a bit of work.

Please bear in mind that it's no one's job (AFAIK) to maintain this repository. It's only spare our time. So the more work you can do on our side to succinctly explain the problem and provide solutions, the more likely we can help.

**Comment by pwaller** [comment]
Also if you don't get a response to a thread in a long time (e.g, weeks, months), please feel free to ping it. It's possible the message was just missed or dropped off the radar.
