### ISSUE TITLE
OpenGL 4.6 support.

### ISSUE THREAD

**Issue by shurcooL** [go-gl/glow#90]
When I did `glow download` in #89, it fetched the latest XML from our current source at `https://cvs.khronos.org/svn/repos/ogl/trunk/doc/registry/public/api/gl.xml`:

```
$ glow download
2017/11/09 19:51:41 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/doc/registry/public/api/wgl.xml
2017/11/09 19:51:41 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/doc/registry/public/api/gl.xml
2017/11/09 19:51:41 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/doc/registry/public/api/egl.xml
2017/11/09 19:51:41 Downloading https://cvs.khronos.org/svn/repos/ogl/trunk/doc/registry/public/api/glx.xml
...
```

However, even the latest version of that repository, at this moment, does not yet contain definitions for OpenGL 4.6. It contains 4.5 as the latest version.

The alternative source at `https://raw.githubusercontent.com/KhronosGroup/OpenGL-Registry/master/xml/gl.xml` that @kjozic found contains 4.6.

We need to decide what to do to add support for OpenGL 4.6 to `glow`:

1. Do we wait until the current source adds 4.6? Any way to find out when that will happen?
2. Do we change the default source where we fetch our XML files? But what about the doc XML files and egl.xml which isn't present in https://github.com/KhronosGroup/OpenGL-Registry/tree/master/xml?

/cc @errcw Need your input on this decision.

**Comment by errcw** [comment]
I believe the right answer is to change the default source where we fetch the XML files. It appears that Khronos maintains its GitHub repositories but not its SVN ones. Unfortunately it means pulling the files from more locations. The docs appear to be located in https://github.com/KhronosGroup/OpenGL-Refpages, and egl.xml appears to be located in https://github.com/KhronosGroup/EGL-Registry. Perhaps the easiest answer is to remove the download command and instead add documentation from where to fetch the files?

**Comment by kjozic** [comment]
I rewrote main.go and download.go ([link](https://github.com/kjozic/glow), branch OpenGL4.6) to fetch the XML files from GitHub but there is a problem with hourly [rate limit](https://developer.github.com/v3/#rate-limiting). For unauthenticated requests, the rate limit is 60 requests per hour which is not enough to download all the files.

**Comment by shurcooL** [comment]
We can make it a requirement to supply a github token to get the authenticated rate limit of 5000 per hour.

**Comment by kjozic** [comment]
I made support for GitHub basic auth.

**Comment by errcw** [comment]
I'm attempting to resolve this in https://github.com/go-gl/glow/pull/92.

**Comment by shurcooL** [comment]
@errcw Did you see #91 before making #92?

**Comment by kjozic** [comment]
When I try to download gl.xml, the empty file is returned. The error is caused because of file size:
```
{
  "message": "This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size.",
  "errors": [
    {
      "resource": "Blob",
      "field": "data",
      "code": "too_large"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/repos/contents/#get-contents"
}
```

**Comment by shurcooL** [comment]
Is this issue resolved by #91 (which has been merged by now)?

**Comment by kjozic** [comment]
Yes. You can close the issue.

**Comment by shurcooL** [comment]
We should download and commit the latest XML from the new source to fully resolve this issue. Reopening for that.
